controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\SecurityController::index

accueil_app:
    path: /accueil
    controller: App\Controller\SecurityController::index
